applications:
- api_domain: devcp1.ozonecloud.ai
  application_name: ozone-api-server-dev
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://raw.githubusercontent.com/qct/swagger-example/master/swagger-server/src/main/resources/swagger.yml
  type: api
